name: Deploy Pipeline

on:
  release:
    types:
      - published

jobs:
  deploy-stage:
    name: Deploy Stage
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to Stage"

  approve-prod:
    name: Approve Production Deployment
    runs-on: ubuntu-latest
    environment: prod-approval
    concurrency:
      group: prod-approval 
    needs:
      - deploy-stage
    steps:
      - run: echo "Deployment approved, moving on"

  deploy-prod:
    name: Deploy Prod
    needs:
      - approve-prod
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to Production"

